version: "3.8"

services:
  nouvelair:
    container_name: nouvelair
    build: ./nouvelair_api
    restart: on-failure
    ports:
      - 9090:9090
    networks:
      - app_net


  technical_rms:
    container_name: technical_rms
    build: ./technical_test_RMS
    ports:
      - 8081:8081
    environment:
      SPRING_APPLICATION_JSON: '{
        "repositories.nouvelair.flights.api.url"  : "http://localhost:9090/nouvelair/flights",
        "repositories.tunisair.flights.api.url" : "http://localhost:9080/tunisair/flights"
      }'
    networks:
      - app_net


  tunisair:
    container_name: tunisair
    build: ./nouvelair_api
    restart: on-failure
    ports:
      - 9080:9090
    networks:
      - app_net

networks:
  app_net:
    driver: bridge